# Generated by Django 4.0.5 on 2022-06-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanageapp', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1salary',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2salary',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3salary',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
