# Generated by Django 4.0.5 on 2022-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanageapp', '0003_alter_employeeexperience_company1salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
