# Generated by Django 4.0.5 on 2022-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanageapp', '0004_alter_employeeexperience_company1salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3duration',
            field=models.IntegerField(null=True),
        ),
    ]
