# Generated by Django 4.0.5 on 2022-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanageapp', '0006_rename_user_employeeexperience_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='experience',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagegra',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagehsc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagepg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
