# Generated by Django 4.0.5 on 2022-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanageapp', '0007_rename_experience_employeeexperience_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcegra',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcehsc',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcepg',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcessc',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagegra',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagehsc',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagepg',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclggra',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclghsc',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclgpg',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclgssc',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingpg',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingra',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingssc',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1desig',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1duration',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1salary',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2desig',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2duration',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2salary',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3desig',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3duration',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3salary',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
