# Generated by Django 4.0.5 on 2022-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanageapp', '0008_employeedetail_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperience',
            name='company1name',
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcegra',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcehsc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcepg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='courcessc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagegra',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagehsc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagepg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclggra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclghsc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclgpg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclgssc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingpg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingra',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingssc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1desig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2desig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3desig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
